# Paths to ignore when scanning for source files
ignorePaths:
- "Pods"
- "Frameworks"
- "Products"

# Allowed file types to include when scanning
allowFileTypes:
- "sourcecode.swift"      # Swift source code files
- "sourcecode.c.objc"     # Objective-C source code files
- "sourcecode.cpp.objcpp" # Objective-C++ source code files  
- "sourcecode.c.h"        # C/Objective-C header files
- "file.xib"             # Interface Builder XIB files
- "file.storyboard"      # Interface Builder Storyboard files
- "folder.assetcatalog"  # Asset catalog containing images and resources
- "text.json.xcstrings"  # Localized strings in JSON format
- "text.plist.strings"   # Localized strings in plist format

# Whether to move files only, without changing .xcodeproj settings
moveFileOnly: false
